menu:
  - id: home
    link: /
    icon: home
    class: menu-home

  - id: about
    link: /about
    icon: user
    class: menu-about
    
  - id: reading
    link: /reading
    icon: book
    class: menu-reading

  - id: download


# 颜色配置
color:
  header: indigo
  footer: indigo
  page_nav: indigo
  side_nav: indigo darken-1
  tag: green lighten-1
  article_title_link: indigo
  link: pink
  pagination: pink
  tab: pink
  archive_item: grey
  fab: pink
  fab_2: green
  fab_3: yellow darken-1 
  new: pink
  about_header: indigo
  about_title: indigo


google_code_prettify: prettify-tomorrow-night-eighties