[package]
name = "ds-static-topo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
ciborium = "0.2"
arrow-schema = { version = "53.3", features = ["serde"] }
petgraph = "0.6"
mems = { path = "../../.." }
bytes = "1.8"