[package]
name = "ds-common"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
serde_json = "1.0"
csv = "1.3.0"
eig-domain = { path = "../../../eig-domain" }
mems = { path = "../../../mems" }