[package]
name = "ds-tn-input"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
serde_cbor = "0.11"
arrow-schema = { version = "52.1", features = ["serde"] }
mems = { path = "../../../mems" }