[package]
name = "eig-domain"
version = "0.1.0"
authors = ["dongshufeng <dongshufeng@zju.edu.cn>"]
edition.workspace = true
rust-version.workspace = true
build = "build.rs"

[dependencies]
log = "0.4"
bytes = "1.6"
byteorder = "1.5"
lazy_static = "1.5"
csv = "1.3"
calamine = { version = "0.25" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
protobuf = { version = "3.5", features = ["with-bytes"] }
encoding_rs = "0.8"
zip = { version = "2.1", default-features = false, features = ["deflate"] }
tempfile = { version = "3.10" }
walkdir = { version = "2.5" }

# this project
eig-expr = { path = "../eig-expr"}

[build-dependencies]
# protobuf-codegen-pure = "2.28"
protobuf-codegen = "3.5"
protobuf = { version = "3.5", features = ["with-bytes"] }